apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

images:
  - name: hoangdonguit/gitops-cicd-demo-app
    newTag: sha-2218381
