apiVersion: v1
kind: Service
metadata:
  name: gitops-cicd-demo-app
  labels:
    app: gitops-cicd-demo-app
spec:
  type: ClusterIP
  selector:
    app: gitops-cicd-demo-app
  ports:
    - name: http
      port: 80
      targetPort: http
