apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - ../../base
  - ingress.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      environment: p2-platform
    includeSelectors: true

patches:
  - path: deployment-label-patch.yaml
