apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitops-cicd-demo-app
  labels:
    app.kubernetes.io/name: gitops-cicd-demo-app
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: gitops-cicd-demo-app
      environment: p2-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
